site_name: MuCSL Autonomous Robotic Platform Documentations
site_url: https://github.com/Ericc99/mucsl-arp/
site_author: Eric CUI
theme: readthedocs
nav:
  - General Information: index.md

# Publish Command to Github Pages
# cd site
# mkdocs gh-deploy --clean

# !!! 注意 !!! 
# Github Push 只会修改 GitHub 上面的源文件
# Publish 指令只会修改 gh-pages 上面的网页文件
# 两者不是一回事